// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docSidebar: [
    {
      type: "category",
      label: "Introduction",
      link: { type: "doc", id: "index" },
      collapsed: false,
      items: [
        "architecture",
        "roadmap",
        "x402-payments",
        "llms-txt"
      ]
    },
    {
      type: "category",
      label: "DIN as an AVS",
      link: { type: "doc", id: "avs/index" },
      collapsed: true,
      items: [
        "avs/onboard",
        "avs/slashing-and-rewards",
        "avs/operator-sets",
        "avs/veto-committee"
      ]
    },
    {
      type: "category",
      label: "Node providers",
      link: { type: "doc", id: "node-providers/index" },
      collapsed: true,
      items: [
        "node-providers/onboard"
      ]
    },
    {
      type: "category",
      label: "Watchers",
      link: { type: "doc", id: "watchers/index" },
      collapsed: true,
      items: [
        "watchers/onboard",
        "watchers/make-api-requests",
        "watchers/monitor-health"
      ]
    },
    {
      type: "category",
      label: "Web3 gateways",
      link: { type: "doc", id: "web3-gateways/index" },
      collapsed: true,
      items: [
        "web3-gateways/onboard",
        "web3-gateways/monitor-usage",
        "web3-gateways/manage-payments",
        "web3-gateways/view-api-pricing"
      ]
    }
  ],
  apiSidebar: [
    "api-reference/supported-networks",
    {
      type: "category",
      label: "API reference",
      collapsed: false,
      items: [
        {
          type: "category", 
          label: "Ethereum",
          link: { type: "doc", id: "api-reference/ethereum/index" },
          collapsed: true,
          items: [
            {
              type: "category",
              label: "JSON-RPC methods",
              collapsed: false,
              items: [
                {
                  type: "autogenerated",
                  dirName: "api-reference/ethereum/json-rpc-methods"
                }
              ]
            }
          ]
        },
        {
          type: "category", 
          label: "Solana",
          link: { type: "doc", id: "api-reference/solana/index" },
          collapsed: true,
          items: [
            {
              type: "category",
              label: "JSON-RPC methods",
              collapsed: false,
              items: [
                {
                  type: "autogenerated",
                  dirName: "api-reference/solana/json-rpc-methods"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
};

module.exports = sidebars;
