// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docSidebar: [
    {
      type: "category",
      label: "Introduction",
      link: { type: "doc", id: "index" },
      collapsed: false,
      items: [
        "architecture",
        "roadmap",
        "x402-payments",
        "llms-txt"
      ]
    },
    {
      type: "category",
      label: "DIN as an AVS",
      link: { type: "doc", id: "avs/index" },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Onboard as an operator",
          link: { type: "doc", id: "avs/operator-onboarding/index" },
          items: [
            "avs/operator-onboarding/prerequisites",
            "avs/operator-onboarding/mainnet-preparation",
            {
              type: "category",
              label: "Onboard with the DIN app",
              link: { type: "doc", id: "avs/operator-onboarding/onboard/index" },
              collapsed: false,
              items: [
                "avs/operator-onboarding/onboard/register-operator",
                "avs/operator-onboarding/onboard/stake-tokens",
                "avs/operator-onboarding/onboard/allocation-delay",
                "avs/operator-onboarding/onboard/watchers",
                "avs/operator-onboarding/onboard/opt-in-avs"
              ]
            },
            "avs/operator-onboarding/troubleshoot"
          ]
        },
        "avs/slashing-and-rewards",
        "avs/operator-sets",
        "avs/veto-committee"
      ]
    },
    {
      type: "category",
      label: "Node providers",
      link: { type: "doc", id: "node-providers/index" },
      collapsed: true,
      items: []
    },
    {
      type: "category",
      label: "Watchers",
      link: { type: "doc", id: "watchers/index" },
      collapsed: true,
      items: [

      ]
    },
    {
      type: "category",
      label: "Web3 gateways",
      link: { type: "doc", id: "web3-gateways/index" },
      collapsed: true,
      items: [
        "web3-gateways/onboard",
        "web3-gateways/monitor-usage"
      ]
    }
  ],
  apiSidebar: [
    "api-reference/supported-apis",
    {
      type: "category",
      label: "Networks",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Arbitrum",
          link: { type: "doc", id: "api-reference/arbitrum/index" },
          collapsed: true,
          items: [
            {
              type: "category",
              label: "Ethereum JSON-RPC API",
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "api-reference/arbitrum/json-rpc-api"
                }
              ]
            }
          ]
        },
        {
          type: "category", 
          label: "Base",
          link: { type: "doc", id: "api-reference/base/index" },
          collapsed: true,
          items: [
            {
              type: "category",
              label: "Ethereum JSON-RPC API",
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "api-reference/base/json-rpc-api"
                }
              ]
            }
          ]
        },
        {
          type: "category", 
          label: "Blast",
          link: { type: "doc", id: "api-reference/blast/index" },
          collapsed: true,
          items: [
            {
              type: "category",
              label: "Ethereum JSON-RPC API",
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "api-reference/blast/json-rpc-api"
                }
              ]
            }
          ]
        },
        {
          type: "category", 
          label: "BNB Smart Chain",
          link: { type: "doc", id: "api-reference/bnb-smart-chain/index" },
          collapsed: true,
          items: [
            {
              type: "category",
              label: "Ethereum JSON-RPC API",
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "api-reference/bnb-smart-chain/json-rpc-api"
                }
              ]
            }
          ]
        },
        {
          type: "category", 
          label: "Ethereum",
          link: { type: "doc", id: "api-reference/ethereum/index" },
          collapsed: true,
          items: [
            {
              type: "category",
              label: "Core JSON-RPC API",
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "api-reference/ethereum/json-rpc-api"
                }
              ]
            },
            {
              type: "category",
              label: "Trace API",
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "api-reference/ethereum/trace-api"
                }
              ]
            }
          ]
        },
        {
          type: "category",
          label: "Mantle",
          link: { type: "doc", id: "api-reference/mantle/index" },
          collapsed: true,
          items: [
            {
              type: "category",
              label: "Ethereum JSON-RPC API",
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "api-reference/mantle/json-rpc-api"
                }
              ]
            },
            {
              type: "category",
              label: "Debug API",
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "api-reference/mantle/debug-api"
                }
              ]
            }
          ]
        },
        {
          type: "category",
          label: "Optimism",
          link: { type: "doc", id: "api-reference/optimism/index" },
          collapsed: true,
          items: [
            {
              type: "category",
              label: "Ethereum JSON-RPC API",
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "api-reference/optimism/json-rpc-api"
                }
              ]
            }
          ]
        },
        {
          type: "category",
          label: "Polygon PoS",
          link: { type: "doc", id: "api-reference/polygon-pos/index" },
          collapsed: true,
          items: [
            {
              type: "category",
              label: "Ethereum JSON-RPC API",
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "api-reference/polygon-pos/json-rpc-api"
                }
              ]
            },
            {
              type: "category",
              label: "Bor API",
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "api-reference/polygon-pos/bor-api"
                }
              ]
            }
          ]
        },
        {
          type: "category",
          label: "Solana",
          link: { type: "doc", id: "api-reference/solana/index" },
          collapsed: true,
          items: [
            {
              type: "category",
              label: "Core JSON-RPC API",
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "api-reference/solana/json-rpc-api"
                }
              ]
            },
            {
              type: "category",
              label: "Digital Asset Standard API",
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "api-reference/solana/digital-asset-standard-api"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
};

module.exports = sidebars;
