// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docSidebar: [
    {
      type: "category",
      label: "Overview",
      collapsed: false,
      items: [
        "din/overview/introduction",
        "din/overview/architecture-overview"
      ]
    },
    {
      type: "category",
      label: "Gateways",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "din/gateways"
        }
      ]
    },
    {
      type: "category", 
      label: "DIN as an AVS",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "din/avs"
        }
      ]
    },
    {
      type: "category",
      label: "Reference",
      collapsed: true, 
      items: [
        {
          type: "autogenerated",
          dirName: "din/reference"
        }
      ]
    }
  ],
  apiSidebar: [
    "api-reference/supported-networks",
    {
      type: "category",
      label: "API reference",
      collapsed: false,
      items: [
        {
          type: "category", 
          label: "Ethereum",
          collapsed: true,
          items: [
            {
              type: "category",
              label: "JSON-RPC methods",
              collapsed: false,
              items: [
                {
                  type: "autogenerated",
                  dirName: "api-reference/ethereum/json-rpc-methods"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
};

module.exports = sidebars;
