---
name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Build once and share artifact with deployment jobs
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create Vercel output structure
        run: |
          mkdir -p .vercel/output
          cp -r build .vercel/output/static
          echo '{"version": 3}' > .vercel/output/config.json

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: .vercel/output/
          retention-days: 1

  lint:
    name: Lint Code Base, Spelling
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Lint code
        uses: ConsenSys/github-actions/docs-lint-all@main

      - name: Lint markdown
        uses: ConsenSys/github-actions/docs-lint-markdown@main

  link-check:
    name: Link Checking
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file-extensions: [".md", ".mdx"]
    steps:
      - uses: actions/checkout@v4

      - name: LinkCheck
        uses: ConsenSys/github-actions/docs-link-check@main
        with:
          FILE_EXTENSION: ${{ matrix.file-extensions }}

  case-check:
    name: Check for case being inconsistent
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ["docs"]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Case check action
        uses: ConsenSys/github-actions/docs-case-check@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOC_DIR: ${{ matrix.folder }}
          SKIP_TEST: true

  # Preview deployment for PRs - reuses build artifact
  preview-deploy:
    name: Deploy Preview to Vercel
    if: github.event_name == 'pull_request'
    needs: [build, lint, link-check, case-check]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .vercel/output/

      - name: Deploy to Vercel (Preview)
        uses: amondnet/vercel-action@v25
        id: vercel-preview
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prebuilt'
          github-comment: true

  # Production deployment - reuses build artifact
  production-deploy:
    name: Deploy Production to Vercel
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [build, lint, link-check, case-check]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .vercel/output/

      - name: Deploy to Vercel (Production)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod --prebuilt'

  # Semantic release - runs after production deploy
  release:
    name: Create Release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: production-deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Release
        uses: Consensys/github-actions/docs-release@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEMANTIC_RELEASE: true
