---
name: Spelling Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  spelling:
    name: Vale Spelling and Style Check
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Vale
        uses: Consensys/github-actions/docs-spelling-check@main
        with:
          FILEPATHS: "docs"
